export {default as Home} from './Homepage'
export {default as Movies} from './Movies'
export {default as TvSeries} from './TvSeries'
export {default as Favorites} from './Favorites'
export {default as Detail} from './Detailpage'
export {default as Addpage} from './Addpage'
export {default as Editpage} from './Editpage'